### ISSUE TITLE
Uglify isn't running inside the @suports tag

### ISSUE THREAD

**Issue by M-J-Robbins** [RebelMail/html-uglify#14]
When wrapping my code in this 

```
@supports (animation) {
    /*CSS*/
}
```

It appears to be skipped by uglify, so the CSS selectors no longer match the HTML classes.  Removing the `@supports` query fixes the issue.

**Comment by elbuo8** [comment]
@motdotla @M-J-Robbins still active?

**Comment by M-J-Robbins** [comment]
Yeah still active :(

**Comment by motdotla** [comment]
I'll try and work on this today.

**Comment by motdotla** [comment]
https://github.com/Rebelmail/html-uglify/pull/21/files

**Comment by motdotla** [comment]
@M-J-Robbins give this a shot now. You should be good to go.

**Comment by M-J-Robbins** [comment]
:+1:
