### ISSUE TITLE
split out to posthtml plugins

### ISSUE THREAD

**Issue by stevenvachon** [RebelMail/html-uglify#22]
Modular, and can be used with other plugins.

**Comment by devinus** [comment]
https://github.com/Rebelmail/posthtml-uglify

**Comment by stevenvachon** [comment]
That's not a replacement for this library, though.

**Comment by devinus** [comment]
@stevenvachon How not?

**Comment by stevenvachon** [comment]
Oh, wow, I was totally under the impression that this library did what [html-minifier](https://npmjs.com/html-minifier) does.
