### ISSUE TITLE
Support whitelisting

### ISSUE THREAD

**Issue by devinus** [RebelMail/html-uglify#6]

**Comment by elbuo8** [comment]
Whitelist what?

**Comment by motdotla** [comment]
This is related to slif-extension here: https://github.com/RebelMail/slif-extension/issues/9

**Comment by devinus** [comment]
@elbuo8 Class and ID names.

**Comment by devinus** [comment]
@motdotla I can start this.

**Comment by motdotla** [comment]
:heart:

**Comment by motdotla** [comment]
I've got bandwidth right now. Taking this on.

**Comment by motdotla** [comment]
closed.
